# Generated by Django 2.2 on 2019-04-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='orders.Menu')),
            ],
        ),
    ]
