# Generated by Django 2.2 on 2019-04-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='intype',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='orders.FoodType'),
        ),
    ]
