# Generated by Django 2.2 on 2019-04-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190404_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaToppingsForPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberoftoppings', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.FoodType'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsForPricing'),
        ),
    ]
