# Generated by Django 2.2 on 2019-04-04 11:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0004_auto_20190404_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaToppingsForPricing',
            new_name='PizzaToppingsTypes',
        ),
    ]
