# Generated by Django 2.2 on 2019-04-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190404_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='pizzatoppingstypes',
            old_name='topping_type',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.MenuPriority'),
        ),
    ]
