# Generated by Django 2.2 on 2019-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190404_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menupriority',
            old_name='priority',
            new_name='name',
        ),
        migrations.AddField(
            model_name='menupriority',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
