# Generated by Django 2.2 on 2019-04-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190404_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_priority',
            field=models.ForeignKey(default='Normal', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.MenuPriority'),
        ),
    ]
