# Generated by Django 2.2 on 2019-04-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190404_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.MenuPriority'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsTypes'),
        ),
    ]
