# Generated by Django 2.2 on 2019-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190404_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsTypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzatoppingstypes',
            name='topping_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
