# Generated by Django 2.2 on 2019-04-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190404_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsTypes'),
        ),
        migrations.AlterField(
            model_name='pizzatoppingstypes',
            name='topping_type',
            field=models.CharField(default=999, max_length=64),
            preserve_default=False,
        ),
    ]
