# Generated by Django 2.2 on 2019-04-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190404_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsTypes'),
        ),
    ]
