# Generated by Django 2.2 on 2019-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190404_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatoppingstypes',
            name='topping_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
