# Generated by Django 2.2 on 2019-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190404_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatoppingstypes',
            name='topping_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
