# Generated by Django 2.2 on 2019-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190404_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatoppingstypes',
            name='topping_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
