# Generated by Django 2.2 on 2019-04-06 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190405_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderlist',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
