# Generated by Django 2.2 on 2019-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20190406_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_done',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=999, max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderlist',
        ),
        migrations.AddField(
            model_name='order',
            name='orderlist',
            field=models.CharField(default=999, max_length=64),
            preserve_default=False,
        ),
    ]
