# Generated by Django 2.2 on 2019-04-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20190406_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.Menu'),
        ),
    ]
