# Generated by Django 2.2 on 2019-04-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20190406_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default='Prepairing', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.Order_State'),
        ),
    ]
