# Generated by Django 2.2 on 2019-04-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20190412_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['food_type', 'toppings_type', 'size']},
        ),
    ]
