# Generated by Django 2.2 on 2019-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20190414_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderlist',
        ),
        migrations.AddField(
            model_name='order',
            name='orderlist',
            field=models.ManyToManyField(related_name='orders', to='orders.Menu'),
        ),
    ]
