# Generated by Django 2.2 on 2019-04-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20190415_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderlist',
        ),
    ]
