# Generated by Django 2.2 on 2019-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_remove_order_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderlist',
            field=models.ManyToManyField(related_name='orders', through='orders.Quantity', to='orders.Menu'),
        ),
    ]
