# Generated by Django 2.2 on 2019-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderlist2',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
