# Generated by Django 2.2 on 2019-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20190415_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
    ]
