# Generated by Django 2.2 on 2019-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_pizzatoppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='number_of_toppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
