# Generated by Django 2.2 on 2019-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_menu_number_of_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
