# Generated by Django 2.2 on 2019-04-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20190429_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Single_Order_Item',
        ),
    ]
