# Generated by Django 2.2 on 2019-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20190429_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_order_item',
            name='selected_toppings',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
