# Generated by Django 2.2 on 2019-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_single_order_item2'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='in_order',
            field=models.ManyToManyField(blank=True, related_name='in_menu', to='orders.Single_Order_Item2'),
        ),
    ]
