# Generated by Django 2.2 on 2019-04-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20190429_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order', to='orders.Order'),
        ),
    ]
