# Generated by Django 2.2 on 2019-04-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_auto_20190430_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_menu', to='orders.Menu'),
        ),
    ]
