# Generated by Django 2.2 on 2019-04-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_auto_20190430_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order_item2',
            name='order1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_temp2', to='orders.Order'),
        ),
    ]
