# Generated by Django 2.2.1 on 2019-05-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_auto_20190506_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_priority',
        ),
        migrations.AlterField(
            model_name='menu',
            name='toppings_type',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.PizzaToppingsTypes'),
        ),
    ]
