# Generated by Django 2.2.1 on 2019-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_auto_20190506_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='priority',
            field=models.IntegerField(default=50),
        ),
    ]
