# Generated by Django 2.2.1 on 2019-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_menu_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='comment',
            field=models.CharField(default='', max_length=64),
        ),
    ]
