# Generated by Django 2.2.1 on 2019-05-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_menu_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatoppings',
            name='group',
            field=models.CharField(default='nogroup', max_length=64),
        ),
    ]
