# Generated by Django 2.2.1 on 2019-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_pizzatoppings_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show',
            field=models.IntegerField(default=1),
        ),
    ]
