# Generated by Django 2.2.1 on 2019-05-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_auto_20190506_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='show',
        ),
    ]
