# Generated by Django 2.2.1 on 2019-05-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_menu_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_order_item',
            name='item',
        ),
    ]
