# Generated by Django 2.2.1 on 2019-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_remove_single_order_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_order_item',
            name='item',
            field=models.CharField(default='', max_length=128),
        ),
    ]
